# Generated by Django 5.1.3 on 2026-03-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_module_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Число для вставки: в тексте пишите [рис. 1]', max_length=20, verbose_name='Ключ (номер)')),
                ('caption', models.CharField(help_text='Например: Рисунок 1', max_length=200, verbose_name='Подпись')),
                ('image', models.ImageField(upload_to='text_figures/', verbose_name='Изображение')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='courses.text')),
            ],
            options={
                'verbose_name': 'Рисунок в тексте',
                'verbose_name_plural': 'Рисунки в тексте',
                'ordering': ['key'],
                'unique_together': {('text', 'key')},
            },
        ),
    ]
